CREATE TABLE user (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user VARCHAR(64) NOT NULL UNIQUE ,
    password VARCHAR(64) NOT NULL,
    date TIMESTAMP

);

create table info (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    age int(2) NOT NULL,
    location VARCHAR(256) NOT NULL,
    date TIMESTAMP
);

CREATE TABLE plan (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    skill int(32) NOT NULL,
    goal int(32) NOT NULL,
    plan VARCHAR(256) NOT NULL,
    date TIMESTAMP NOT NULL
);



